### ISSUE TITLE
Setup tasks scheduling for services

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode-generic#11]
A common scheduling system must be used and managed to drive backups and monitoring tasks.
Rancher cron sheduling features should be considered.

connected to #3
connected to #4

**Comment by randomorder** [comment]
We could use Rancher CRON service to trigger a container run on a schedule or a dedicated  container running 24/7 with CRON daemon.
First option owuld be Rancher specific of course. @giohappy  and I discussed this briefly and we agreed to go for the second option
