### ISSUE TITLE
Layer upload not working

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode-generic#25]
New layer upload creates the GeoNode layer instance but not store/layer in Geoserver.
Tested on http://slave1.rancher.geonode.geo-solutions.it

**Comment by cezio** [comment]
This is because we use `OGC_SERVER['default']['USER']` and `OGC_SERVER['default']['PASSWORD']` from `settings` to access GS REST API. Admin user password was changed in GS UI, but not in settings.  Reverting it to value from settings fixed upload problem.

**Comment by giohappy** [comment]
this forces us to define a rancher question / docker env to define the GS admin pw. We cannot keep the default one.

**Comment by giohappy** [comment]
fixed in #23
