### ISSUE TITLE
Implement restore procedure

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode-generic#34]
Currently geonode-generic includes scheduled backups (geosolutionsit/geonode-backup:latest image) but we need to implement a restore procedure for disaster recovery scenarios.

Assuming [external volume has been configured](https://github.com/geosolutions-it/geonode-generic/blob/master/templates/geonode-generic/0/rancher-compose.yml#L90) for backups storage we need to have the following procedure implemented and tested:

1. geonode-generic stack running with backups available
2. stack gets corrupted / destroyed 
3. a new geonode-generic stack is create
4. previous backups are restored -> new stack should be in the exactly the same state as the previous one (data, users, credentuals, etc.)

**The goal is to have a recovery procedure that guarantees stack restoration in the worst scenario, that can be simulated restoring a stack in a brand new host**.

For this task a new "geonode-restore" image should be defined. It will use the same configuration (env vars) fro Rancher / Docker as the other containers in the stack.

Recovery procedure steps:

1. Create new stack **without starting the containers**
2. Run the PostGIS container (for pg_restore)
2. Run the geonode-restore container and wait its completion
3. Run the other containers

**For the moment this will be documented and executed manually**. In the future an automated mechanis, under orchestration, will be implemented.

**Comment by cezio** [comment]
Fixed with https://github.com/geosolutions-it/geonode-restore-docker/pull/1

Restore proc described in 
https://github.com/cezio/geonode-restore-docker/blob/master/README.md
